<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFihzSg4\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFihzSg4/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFihzSg4.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFihzSg4\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerFihzSg4\App_KernelProdContainer([
    'container.build_hash' => 'FihzSg4',
    'container.build_id' => '88042662',
    'container.build_time' => 1602420527,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFihzSg4');
