<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_user_update' => [[], ['_controller' => 'App\\Controller\\ProfileController::updateProfile'], [], [['text', '/profile']], [], []],
    'app_user_show' => [['id'], ['_controller' => 'App\\Controller\\ProfileController::showUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'app_user' => [[], ['_controller' => 'App\\Controller\\ProfileController::showProfile'], [], [['text', '/profile']], [], []],
    'app_user_tasks' => [[], ['_controller' => 'App\\Controller\\ProfileController::showMyTasks'], [], [['text', '/my-tasks']], [], []],
    'app_user_add_task' => [[], ['_controller' => 'App\\Controller\\ProfileController::addTask'], [], [['text', '/my-tasks/add-task']], [], []],
    'app_create_project' => [[], ['_controller' => 'App\\Controller\\ProjectController::addProjectToDB'], [], [['text', '/project/new']], [], []],
    'app_add_project' => [[], ['_controller' => 'App\\Controller\\ProjectController::addProject'], [], [['text', '/project/new']], [], []],
    'app_create_task' => [['project_id'], ['_controller' => 'App\\Controller\\ProjectController::addTaskToDB'], [], [['text', '/task/new'], ['variable', '/', '[^/]++', 'project_id', true], ['text', '/project']], [], []],
    'app_add_task' => [['project_id'], ['_controller' => 'App\\Controller\\ProjectController::addTask'], [], [['text', '/task/new'], ['variable', '/', '[^/]++', 'project_id', true], ['text', '/project']], [], []],
    'app_show_task' => [['project_id', 'task_id'], ['_controller' => 'App\\Controller\\ProjectController::showTask'], [], [['variable', '/', '[^/]++', 'task_id', true], ['text', '/task'], ['variable', '/', '[^/]++', 'project_id', true], ['text', '/project']], [], []],
    'app_edit_task_db' => [['project_id', 'task_id'], ['_controller' => 'App\\Controller\\ProjectController::editTaskToDB'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'task_id', true], ['text', '/task'], ['variable', '/', '[^/]++', 'project_id', true], ['text', '/project']], [], []],
    'app_edit_task' => [['project_id', 'task_id'], ['_controller' => 'App\\Controller\\ProjectController::editTask'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'task_id', true], ['text', '/task'], ['variable', '/', '[^/]++', 'project_id', true], ['text', '/project']], [], []],
    'app_edit_project_db' => [['project_id'], ['_controller' => 'App\\Controller\\ProjectController::editProjectToDB'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'project_id', true], ['text', '/project']], [], []],
    'app_edit_project' => [['project_id'], ['_controller' => 'App\\Controller\\ProjectController::editProject'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'project_id', true], ['text', '/project']], [], []],
    'app_show_project' => [['project_id'], ['_controller' => 'App\\Controller\\ProjectController::showProject'], [], [['variable', '/', '[^/]++', 'project_id', true], ['text', '/project']], [], []],
    'ajax_req' => [['str'], ['_controller' => 'App\\Controller\\ProjectController::findByPriority'], [], [['variable', '/', '[^/]++', 'str', true], ['text', '/ajax']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\SecurityController::register'], [], [['text', '/register']], [], []],
    'app_homepage' => [[], ['_controller' => 'App\\Controller\\SiteController::homepage'], [], [['text', '/']], [], []],
    '' => [[], ['_controller' => 'App\\Controller\\SiteController::addTeamToDB'], [], [['text', '/new-team']], [], []],
    'app_add_team' => [[], ['_controller' => 'App\\Controller\\SiteController::addTeam'], [], [['text', '/new-team']], [], []],
];
