<?php

namespace ContainerWSZPD6n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ROGcGWEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rOGcGWE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rOGcGWE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formAuthenticator' => ['privates', 'App\\Security\\LoginFormAuthenticator', 'getLoginFormAuthenticatorService', true],
            'guardAuthenticatorHandler' => ['privates', 'security.authentication.guard_handler', 'getSecurity_Authentication_GuardHandlerService', true],
            'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
        ], [
            'formAuthenticator' => 'App\\Security\\LoginFormAuthenticator',
            'guardAuthenticatorHandler' => '?',
            'passwordEncoder' => '?',
        ]);
    }
}
