<?php

namespace ContainerWSZPD6n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A54BwBBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A54BwBB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A54BwBB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'project_id' => ['privates', '.errored..service_locator.A54BwBB.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.A54BwBB": it references class "App\\Entity\\Project" but no such service exists.'],
            'task_id' => ['privates', '.errored..service_locator.A54BwBB.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.A54BwBB": it references class "App\\Entity\\Task" but no such service exists.'],
        ], [
            'project_id' => 'App\\Entity\\Project',
            'task_id' => 'App\\Entity\\Task',
        ]);
    }
}
