<?php

namespace ContainerFihzSg4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSiteControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SiteController' shared autowired service.
     *
     * @return \App\Controller\SiteController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SiteController'] = $instance = new \App\Controller\SiteController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\SiteController', $container));

        return $instance;
    }
}
